### ISSUE TITLE
502 Gateway Error on codesandbox

### ISSUE THREAD

**Issue by fatso83** [smart-on-fhir/client-js#155]
Just wanted to alert that when following the example links to [this example](https://4e7rl.codesandbox.io/test.html) and submitting the login, one just gets an error page

```
HttpError: 502 Bad Gateway
URL: https://launch.smarthealthit.org/v/r3/sim/eyJoIjoiMSIsImIiOiJzbWFydC0xNjQyMDY4IiwiZSI6InNtYXJ0LVByYWN0aXRpb25lci03MTYxNDUwMiJ9/fhir/Patient/smart-1642068

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

    at humanizeError (https://4e7rl.codesandbox.io/node_modules/fhirclient/lib/lib.js:216:9)
    at async checkResponse (https://4e7rl.codesandbox.io/node_modules/fhirclient/lib/lib.js:94:11)
    at async Promise.all (index 0)
```

**Comment by vlad-ignatov** [comment]
Can you please check again? The underlying FHIR servers were down when you posted this. Now that they are up, the example seems to work fine for me.

**Comment by fatso83** [comment]
works fine
